backend:
  name: github
  repo: your-username/your-repo
  branch: main
  auth_scope: repo

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "masterlist"
    label: "Masterlist Entries"
    folder: "content/masterlist"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
