backend:
  name: github
  repo: Seucwi-18/Monfleur
   use_graphql: true



media_folder: "images/characters"  # optional; create folder if uploading images
public_folder: "/images/characters"

collections:
  - name: "characters"
    label: "Characters"
    label_singular: "Character"
    folder: "data/characters"
    create: true
    extension: "json"
    format: "json"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Owner", name: "owner", widget: "string" }
      - { label: "Status", name: "status", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Traits", name: "traits", widget: "list", field: {label: "Trait", name: "trait", widget: "string"} }
      - { label: "History", name: "history", widget: "list", fields: [
          {label: "Date", name: "date", widget: "datetime"},
          {label: "Action", name: "action", widget: "string"},
          {label: "By", name: "by", widget: "string"}
        ]}
